title: 'Claire Duparet'
default_lang: en
author:
  name: 'Claire Duparet'
  email: claire.duparet@gmail.com
taxonomies:
  - tags
metadata:
  description: 'Claire Duparet Portfolio'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
