enabled: true
copyright: 'Copyright &copy; Claire Duparet 2017'
favicon: favicon.png
error_header_image: home-bg.jpg
social_icons:
  -
    icon: fa-instagram
    url: 'https://www.instagram.com/claireduparet'
#  -
#    icon: fa-facebook
#    url: 'https://www.facebook.com/claireduparet'
  -
    icon: fa-envelope-o
    url: 'mailto:claire.duparet@gmail.com'  
